service:
  enable: true
  type: ClusterIP
  internalTrafficPolicy: Local
  annotations: {}
  ports:
  - name: grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: http
    port: 4318
    targetPort: 4318
    protocol: TCP